import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Home1</Link>
        </li>
        <li>
          <Link to="/earn">Earn</Link>
        </li>
        <li>
          <Link to="/brandaccount">Brandaccount</Link>
        </li>
        <li>
          <Link to="/creatoraccount">Creatoraccount</Link>
        </li>
        <li>
          <Link to="/dashboardanalyticscreators">
            DashboardAnalyticscreators
          </Link>
        </li>
        <li>
          <Link to="/browsebrands">Browsebrands</Link>
        </li>
        <li>
          <Link to="/framefourteen">FrameFourteen</Link>
        </li>
        <li>
          <Link to="/faq">FAQ</Link>
        </li>
        <li>
          <Link to="/browserextension">Browserextension</Link>
        </li>
        <li>
          <Link to="/buybrands">Buybrands</Link>
        </li>
        <li>
          <Link to="/buycreators">Buycreators</Link>
        </li>
        <li>
          <Link to="/browsecreators">Browsecreators</Link>
        </li>
        <li>
          <Link to="/dashboardwatchlistcreators">
            DashboardWatchlistcreators
          </Link>
        </li>
        <li>
          <Link to="/dashboardanalyticsbrands">DashboardAnalyticsbrands</Link>
        </li>
        <li>
          <Link to="/swapbrands">Swapbrands</Link>
        </li>
        <li>
          <Link to="/swapcreators">Swapcreators</Link>
        </li>
        <li>
          <Link to="/dashboardwatchlistbrands">DashboardWatchlistbrands</Link>
        </li>
        <li>
          <Link to="/faqcommunity">FAQcommunity</Link>
        </li>
        <li>
          <Link to="/slidecover">Slidecover</Link>
        </li>
        <li>
          <Link to="/faqbrandpartner">FAQbrandpartner</Link>
        </li>
        <li>
          <Link to="/slideproduct">SlideProduct</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
